spring:
  application:
    name: demoj
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
    #initialization-mode: always
    sql-script-encoding: UTF-8
#  jpa:
 #   hibernate:
  #    ddl-auto: none
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true    
        
  boot: 
    admin:
      client:
        url : http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
---
spring:
  profiles:
    active: dev
spring.profiles.include:
  - deva
  - devb
---
spring:
  profiles: dev
  security:
    user:
      name: admin
      password: admin

server:
  port: 8081
#  servlet: 
#    context-path: /module-name
  
management.security.enabled: true


---
spring:
  profiles: test
server:
  port: 8088
  
---
spring:
  profiles: deva
message: 1234

---
spring:
  profiles: devb
message: 5678






  